package Network.Events;

public enum EventEnum {
    UPDATE_PLAYERS_LIST, UPDATE_END_GAME,
    UPDATE_PLAYERS_NUMBER,
    UPDATE_TILES_AVAILABILITY,
    UPDATE_CHAIR_OWNER,
    UPDATE_GAME_BOARD,
    UPDATE_GAME_HAS_STARTED,
    UPDATE_CURR_PLAYER,
    UPDATE_REFILL_LIVINGROOM,
    UPDATE_MATCH_WINNER,
    UPDATE_GAME_HAS_ENDED,
    UPDATE_PICKED_LIVINGROOM_TILE,
    UPDATE_PERSONAL_GOAL,
    UPDATE_COMMON_GOAL,
    UPDATE_PLAYER_POINTS,
    UPDATE_STATUS_COMMON_GOAL2,
    UPDATE_STATUS_COMMON_GOAL1,
    UPDATE_PUT_SHELF_TILE,
    UPDATE_CHAT,
    SHOW_IS_GAME_ON

}
