package Util;

public enum CommonGoalType {
    COMMONGOAL01,
    COMMONGOAL02,
    COMMONGOAL03,
    COMMONGOAL04,
    COMMONGOAL05,
    COMMONGOAL06,
    COMMONGOAL07,
    COMMONGOAL08,
    COMMONGOAL09,
    COMMONGOAL10,
    COMMONGOAL11,
    COMMONGOAL12,
}
